parser:
  file:
    inputdir:
    outputdir:
  chunker:
    size: 3

digitalsymbols:
  symbolMap:
    "[ _ | ||_|]": 0
    "[     |  |]": 1
    "[ _  _||_ ]": 2
    "[ _  _| _|]": 3
    "[   |_|  |]": 4
    "[ _ |_  _|]": 5
    "[ _ |_ |_|]": 6
    "[ _   |  |]": 7
    "[ _ |_||_|]": 8
    "[ _ |_| _|]": 9

  reader:
    totalRows: 3
    totalColumns: 3
    symbolsPerLine: 9

logging:
  level:
    root: INFO

